### ISSUE TITLE
Action bar not switching

### ISSUE THREAD

**Issue by JekaLich** [TheLinuxITGuy/Turtle-Dragonflight#10]
tDF 2.1.3

When I use "Stealth" main action bar are not switch for another "stance"
![image](https://github.com/user-attachments/assets/1d6e5bc4-5dec-4662-bb07-0db34afbb179)
![image](https://github.com/user-attachments/assets/041c3bd2-ac41-44a9-b120-c787b3a79bf9)

**Comment by TheLinuxITGuy** [comment]
Unfortunately, I don't see a way around this. The "MainActionBar" art never moves and the buttons are set to overlay on top of it. Essentially, the Stealth bar is under that, which you can't see. Hope this makes sense.

**Comment by TheLinuxITGuy** [comment]
It works, the Stealth bar is just invisible. You can move the abilities you want to that top row, go stealth, then move them into your stealth bar.

**Comment by TheLinuxITGuy** [comment]
Added this to the **Known issues** list for future reference.
