### ISSUE TITLE
Option for grey micro menu causes overlay

### ISSUE THREAD

**Issue by Trust-WoW** [TheLinuxITGuy/Turtle-Dragonflight#11]
With the new option to enable the grey micro menu, it now just shows both styles, overlaying each other.
I already tried deleting the WDB folder.

![WoWScrnShot_080424_125155](https://github.com/user-attachments/assets/ad221328-7828-4670-9a9f-cae49039884f)

**Comment by TheLinuxITGuy** [comment]
Read the prompt when you hover over the option :)

Thanks for testing.
