### ISSUE TITLE
Minimap clock is in 12h format instead of 24h format

### ISSUE THREAD

**Issue by Trust-WoW** [TheLinuxITGuy/Turtle-Dragonflight#17]
In tDF options it says "24 hour clock", but the actual clock above the minimap is in a 12h format.

![image](https://github.com/user-attachments/assets/02f5bffa-6347-4764-a0c9-363a0a3367a5)

**Comment by TheLinuxITGuy** [comment]
Corrected the verbiage of the tooltip

**Comment by Trust-WoW** [comment]
@TheLinuxITGuy 
Is it possible to make the clock 24h or display server time instead?
