### ISSUE TITLE
[Feature Request] Sort bags left to right

### ISSUE THREAD

**Issue by atlasoskar123** [TheLinuxITGuy/Turtle-Dragonflight#19]
Would it be possible to have the option to invert the bag sort? That is, sort left to right.
My OCD likes to keep thing stacked to the left with the main bag empty.

Thank you in advance.

p.s.
Thanks for a great Addon. I love it!

**Comment by TheLinuxITGuy** [comment]
You can edit the mods/tSortBags module if you want.  Line 84
        CONTAINERS = {4, 3, 2, 1, 0}
        make it 0,1,2,3,4
