### ISSUE TITLE
Paladin Auras overlap with Action Bar

### ISSUE THREAD

**Issue by AdrianBuenfil** [TheLinuxITGuy/Turtle-Dragonflight#2]
When changing zones, sometimes the UI reloads some configurations and the Paladin Auras overlap with the Action Bar. The only known way to fix this is to reload the addon, but then after entering a new zone, there's a probability the Auras bar will overlap again.

![Screenshot (7)](https://github.com/TheLinuxITGuy/Turtle-Dragonflight/assets/71770394/6e6ca31a-834a-4c37-8fa6-1c2494bf414d)

**Comment by AdrianBuenfil** [comment]
I think I found the trigger: whenever you open the map, this happens.

**Comment by TheLinuxITGuy** [comment]
Thanks for the feedback. This is an issue I thought I had already addressed. Is this still happening for you?

**Comment by alchem1ster** [comment]
@TheLinuxITGuy 
It may be related, but sometimes the special bars displayed overlap the world map (I use ShaguTweaks that make it windowed).

**Comment by TheLinuxITGuy** [comment]
Can't re-duplicate

**Comment by AdrianBuenfil** [comment]
I downloaded the latest version of the addon and is still happening. But if you can't reproduce, maybe the problem is something else. Thank you for taking a look.

**Comment by alchem1ster** [comment]
Downloaded 1.8.6. 

![image](https://github.com/user-attachments/assets/325de27d-594c-4a9e-b71d-c519d292b86e)

**Comment by alchem1ster** [comment]
@AdrianBuenfil re-open this issue again :)

**Comment by alchem1ster** [comment]
@TheLinuxITGuy

**Comment by TheLinuxITGuy** [comment]
> @TheLinuxITGuy

Ah, so you are running 3 action bars. I've been testing with 2. Let me see if I can add some logic to support this.

**Comment by TheLinuxITGuy** [comment]
@alchem1ster Can you download the latest tDF/tReduced-actionbar.lua and test? Thank you sir.
