### ISSUE TITLE
Bags do not open in version v2.3.3

### ISSUE THREAD

**Issue by ctarx** [TheLinuxITGuy/Turtle-Dragonflight#21]
**Description:**
In the latest update (v2.3.3) of the addon, the bags do not open as expected. This issue occurs both when attempting to open bags using the assigned keybind and when trying to open them via a mouse click. This bug was not present in previous versions.

**Steps to Reproduce:**

- Install and load version v2.3.3 of the addon.
- Attempt to open bags using the assigned keybind.
- Attempt to open bags by clicking on them with the mouse.

**Expected Behavior:**
The bags should open when the keybind is pressed or when clicking on them with the mouse.

**Observed Behavior:**
The bags remain closed, with no response to either the keybind or the mouse click.

**Comment by TheLinuxITGuy** [comment]
Bags work fine

**Comment by edizmetin** [comment]
@ctarx Disable ShaguPlates addon, and for some reason, the bags will work fine.

**Comment by ctarx** [comment]
> @ctarx Disable ShaguPlates addon, and for some reason, the bags will work fine.

Thank you very much, I just came in here to add the same comment as I was checking addon by addon on a new character.
