### ISSUE TITLE
Enemy castbar disappearing on castbar and Unit Frames when using SuperWoW

### ISSUE THREAD

**Issue by Trust-WoW** [TheLinuxITGuy/Turtle-Dragonflight#22]
Regarding https://github.com/TheLinuxITGuy/Turtle-Dragonflight/issues/15, I have tested v2.3.3 and the issue is still there, even with your implementation of ShaguPlates.

If I use the latest standalone version of ShaguPlates, where the issue was [fixed](https://github.com/shagu/ShaguPlates/issues/29#issuecomment-2279734926), it works fine. With the tDF version, it doesn't.

**Comment by TheLinuxITGuy** [comment]
SuperWoW is closed source. Not supported.
