### ISSUE TITLE
Quest Tracking Bug: Missing Progress Text in UI

### ISSUE THREAD

**Issue by Christopher-L-Massie** [TheLinuxITGuy/Turtle-Dragonflight#3]
When trying to track quests without any questing addons installed, the quest tracking feature does not function properly. Unlike the standard UI, where a quick reference for your five tracked quests appears on the screen, there is no text displayed. Could the standard functionality of displaying progress text in the right corner be reinstated?

**Comment by TheLinuxITGuy** [comment]
Typically, pfQuest + pfQuest turtle is used. I removed the default to make it look cleaner.
