### ISSUE TITLE
REQUEST: Free Bag Slots

### ISSUE THREAD

**Issue by DustinChecketts** [TheLinuxITGuy/Turtle-Dragonflight#33]
Just a small request to add an option to display the number of total available bag slots on the main backpack icon in the bottom right. I can't find any of the other addons that do this to be compatible with your AMAZING addon.

**Comment by TheLinuxITGuy** [comment]
Added in 2.5.2, thanks for the suggestion

**Comment by DustinChecketts** [comment]
Awesome! Thank you so much!
