### ISSUE TITLE
Buffs/debuffs and a minimap overlapping

### ISSUE THREAD

**Issue by tonyAndr** [TheLinuxITGuy/Turtle-Dragonflight#34]
![image](https://github.com/user-attachments/assets/ecfae529-944d-4694-9ba5-1cb6ec728373)

Have this issue that curses, poisons, etc are partially hidden behind the minimap. I tried changing ui scale and resolution but the issue persists :/

edit: also forgot to mention, the autoselling of gray junk isn't working for me even tho its activated

**Comment by TheLinuxITGuy** [comment]
CTRL+SHIFT and move them

**Comment by tonyAndr** [comment]
Awesome! Thanks
