### ISSUE TITLE
Options in hidden under SHaguTweaks "Advanced Options" + Lua error

### ISSUE THREAD

**Issue by elfmannen** [TheLinuxITGuy/Turtle-Dragonflight#35]
hi! 

The options button is hidden under the advanced options button when i press escape. I also get a bunch of lua-errors when i cast a spell. Help pls!

**Comment by elfmannen** [comment]
![image](https://github.com/user-attachments/assets/7cdb5d3d-4acf-4008-8ae7-44902d102455)

**Comment by TheLinuxITGuy** [comment]
Don't use with ShaguTweaks. tDF is built on ShaguTweaks.
