### ISSUE TITLE
Minimap scale and buffs\debuffs posiiton

### ISSUE THREAD

**Issue by Oshire** [TheLinuxITGuy/Turtle-Dragonflight#41]
after update minimap scale is way off imo, it looks way too big and because of that  zonename text and buffs/debuffs default position overlap, 1920x1080 resolution.
![image](https://github.com/user-attachments/assets/20cb981f-b330-4d0e-a046-569072d00ba1)

**Comment by TheLinuxITGuy** [comment]
CTRL + SHIFT, you can move. I like the font you are using. What is it?

**Comment by Oshire** [comment]
> CTRL + SHIFT, you can move. I like the font you are using. What is it?

I am sorry for opening ticket for an issue that already been taken care of. i was using the ctrl+shift and moveanyhting to move the buffs/debuffs, but i thought maybe i missed some settings. 

Font is Expressway.ttf

I had to copy it 12 times and rename it to change the fonts in tDF,  because the usual method of simply adding "Fonts" folder to main wow directory was overwritten by tDF fonts) and since there are no font settings atm in the main addon, i just made it so all off the fonts will be the same. i just like the common looks for my ui. thank you for your work!
