### ISSUE TITLE
Zoom button positions are not adjusted for the new square minimap size

### ISSUE THREAD

**Issue by Trust-WoW** [TheLinuxITGuy/Turtle-Dragonflight#44]
Zoom button positions are not yet adjusted for the new square minimap size.

![image](https://github.com/user-attachments/assets/d0edaed3-fc6a-4414-8773-ae5719575cc7)

**Comment by scorpzor** [comment]
Completed in https://github.com/TheLinuxITGuy/Turtle-Dragonflight/releases/tag/v2.6.1

**Comment by Trust-WoW** [comment]
Tested, I can confirm it's fixed.
