### ISSUE TITLE
Free bag slots still showing, even when show bags is disabled

### ISSUE THREAD

**Issue by Trust-WoW** [TheLinuxITGuy/Turtle-Dragonflight#45]
Free bag slots still showing, even when show bags is disabled.
Would be nice if there was an option to also hide the number of free bag slots.

![image](https://github.com/user-attachments/assets/c54e2c82-356e-46a1-82a6-68a89effa905)

**Comment by scorpzor** [comment]
Completed in https://github.com/TheLinuxITGuy/Turtle-Dragonflight/releases/tag/v2.6.1

**Comment by Trust-WoW** [comment]
Tested, I can confirm it's fixed.
