### ISSUE TITLE
Sort bags feature missing from bank frame

### ISSUE THREAD

**Issue by Trust-WoW** [TheLinuxITGuy/Turtle-Dragonflight#58]
Sort bags feature is not available for bank frame, only bag frame.

![image](https://github.com/user-attachments/assets/c946f91d-b4fb-4793-b177-d3c6bbe4728e)

**Comment by edizmetin** [comment]
Completed in: https://github.com/TheLinuxITGuy/Turtle-Dragonflight/pull/59

**Comment by Trust-WoW** [comment]
Tested, can confirm it's working.
