### ISSUE TITLE
Turtle Dragonflight Unitframes (default) no class color in target unit frame

### ISSUE THREAD

**Issue by Trust-WoW** [TheLinuxITGuy/Turtle-Dragonflight#7]
When using the _Turtle Dragonflight Unitframes (default)_ option, the target unit frame will always be a dark blue. It should be displaying the class color (for example yellow for regular mobs or light blue for mage), when used in conjunction with the option _Unit Frame Class Colors_.

![dragonflight](https://github.com/user-attachments/assets/6d2b9754-5654-4164-932f-e459348ca724)
![dragonflight2](https://github.com/user-attachments/assets/504d56be-1656-4ed7-93f8-a70ea8e6c5c9)

**Comment by TheLinuxITGuy** [comment]
Thanks for reporting. Can you snag the latest "tDF/tUnitframes.lua" and test?

**Comment by Trust-WoW** [comment]
Still the same unfortunately. I updated the Addon via GitAddonsManager.

**Comment by TheLinuxITGuy** [comment]
Can you remove your character folders under "twmoa_1171/WTF/Account/USER/Nordanaar" and your WDB folder and try again?

**Comment by Trust-WoW** [comment]
Found a way to reproduce it with the latest version:
Enable "Unit Frame Big Health". If you disable it (which has no effect when using Turtle Dragonflight Unitframes (default) anways, then it works :).

**Comment by TheLinuxITGuy** [comment]
I've had several people test and it works. Can you remove tDF and re-add manually (not GitAddonsManager)?

**Comment by Trust-WoW** [comment]
- uninstalled the Addon via GitAddonsManager and made sure the folder was deleted
- downloaded latest version manually from Github and copied it into Addons folder
- deleted WDB
- deleted tDF.lua 

I can now still reproduce the issue by enabling Unit Frames Big Health. But since this option doesn't do anything anyway when using Turtle Dragonflight Unitframes (default). I will just keep it disabled, then everything else works fine.

**Comment by TheLinuxITGuy** [comment]
Ah, I need to disable **Unit Frame Big Health** while Turtle Dragonflight (default) is checked. 

![image](https://github.com/user-attachments/assets/bf2aeb4c-55d4-41fc-996b-c6578bae8a86)

Thank you so much for testing, really appreciate it.
