### ISSUE TITLE
XP Bar LUA Error entering a City

### ISSUE THREAD

**Issue by KameleonUK** [TheLinuxITGuy/Turtle-Dragonflight#78]
I have the option "Hide XP Outdoors" ticked, when I enter a city and thus the XP bar text would be displayed, when I hve 0% rested XP I get an LUA error in the xpbar-active-tracking.lua line 19 wher is complains about a nil value.

Interface\AddOns\tDF\ mods\xpbar-active-tracking.lua:19: attempt to perform arithmetic on a nil value

**Comment by TheLinuxITGuy** [comment]
Fixed in 2.7.4
