### ISSUE TITLE
Map covering debuffs.

### ISSUE THREAD

**Issue by TomTurbine** [TheLinuxITGuy/Turtle-Dragonflight#79]
Have the settings being default overall. I am using a 1440p resolution with the UI scale set to as small as it can go for the settings I am using.

The debuffs actually start getting covered by the minimap and Atlasloot and ItemRack icons don't follow around the map, they follow around where the default map was and actually go into the maps area if you are trying to rotate their positions.

**Comment by KameleonUK** [comment]
The buffs and debuffs are moveable using the addon's edit mode (hold CTRL and SHIFT), however by default the mini map frame will sit on top of the drag point of the buff bar and the debuff bar.

I solved this my temporarily moving the minimap completely out the way and then moving the buffs / debuffs to their desired position.

As for other addons minimap icon, currently I'm using "MinimapButtonBag-Turtle" from here to get all the adddon icons under one single icon.
https://github.com/McPewPew/MinimapButtonBag-TurtleWoW/archive/refs/heads/master.zip

**Comment by TomTurbine** [comment]
Thanks

**Comment by TheLinuxITGuy** [comment]
See above
