### ISSUE TITLE
Pally Aura Bar

### ISSUE THREAD

**Issue by Whatley187** [TheLinuxITGuy/Turtle-Dragonflight#8]
The Paladin aura bar sits right on top of the bottom left/bottom right action bars. I cannot find any sort of configuration options etc to fix this so I'm assuming its a big of sorts. 
![Screenshot 2024-07-25 013708](https://github.com/user-attachments/assets/30ec6cce-ce55-449b-ab4f-11f64c2b7cd7)

**Comment by TheLinuxITGuy** [comment]
This was fixed back in 1.9, please download the latest and greatest. If that doesn't work, you may also want to delete your WDB folder and characters under "twmoa_1171/WTF/Account/USER/Nordanaar".
