### ISSUE TITLE
When you have multiple NPCs of the same type on screen and one casts a spell, all of them show the cast bar.

### ISSUE THREAD

**Issue by TomTurbine** [TheLinuxITGuy/Turtle-Dragonflight#80]
Noticed this when I was questing, had 3 of the same type of mob on screen and one of them started casting a spell and all 3 of them showed the cast bar even though 2 of them weren't even in combat at that point.

**Comment by Jean-Tinland** [comment]
I think this is a client limitation. Game doesn't differentiate mobs with same names in the nameplates.

**Comment by TomTurbine** [comment]
Ah, understood. Can't wait to see what they do with the 2.0 release and the new changes that can be made.
