### ISSUE TITLE
Missing Microbar

### ISSUE THREAD

**Issue by Shivy001** [TheLinuxITGuy/Turtle-Dragonflight#86]
Even with every other mod disabled, the Microbar / Micromenu doesn't appear. The option to disable the microbar is also not ticked, so unless there is some other way to make it appear, I'm pretty sure it's a problem on the addon part.

**Comment by TVBrowntown** [comment]
yeah, turtle-wow changed the names of a bunch of the buttons and whatnot that this had hooked into will need updating. currently looking into it.

**Comment by Shivy001** [comment]
Thanks for quick answer. everything else looks fine as of now, while testing stuff.

**Comment by TVBrowntown** [comment]
I've had a look at MAY have fixed it. I'm not too sure since the LFG tool is busted currently so I can't really finish it off past that. I'll add a pull request here later when that is resolved - for now to prevent errors turn off the microbar :(

**Comment by Shivy001** [comment]
Legend, and while you are at it, check if buff/debuff window is overlapping minimap, or is that problem on my part. Fixed it with Move Everything, but i think that might also be part of this addon.

**Comment by TVBrowntown** [comment]
> Legend, and while you are at it, check if buff/debuff window is overlapping minimap, or is that problem on my part. Fixed it with Move Everything, but i think that might also be part of this addon.

if you holf ctrl and shift you will be able to move it without using move anything :) not sure why it doesnt align properly from to the map, hadn't looked but I can take a look

**Comment by Shivy001** [comment]
Hmm, thats convinient. Thanks for info.
If i spot anything ill just hit u up in this thread:)
Thanks again for fast response

**Comment by TheLinuxITGuy** [comment]
Appears fixed
