### ISSUE TITLE
Action bar background and border

### ISSUE THREAD

**Issue by edizmetin** [TheLinuxITGuy/Turtle-Dragonflight#9]
Hello,

Thank you for the beautiful UI. I've been using it for a while, and one thing bothers me. The background and borders of the action bars don't look similar to what is shown in your video. I've tried running the game with only your addon active, and it still looks different.

I will attach an example image.

This is how it looks in-game:
![image](https://github.com/user-attachments/assets/0c8299d0-f58a-449c-a163-4f33f1a54033)

This is from your video:
![image](https://github.com/user-attachments/assets/bb784cc1-f442-45d5-8626-8c4d70b779e3)

Thank you!

**Comment by TheLinuxITGuy** [comment]
Thanks! I'm glad you like it.

You can set the actionbars to not always show if you don't want to see the empties. The art for the mainbar was reverted when 2.0 came out. I feel like the quality of the original is better than the low quality one I had before. I want to re-do it to look more like Dragonflight. Stay tuned for that.

Will look like this when it's done:

![Untitled](https://github.com/user-attachments/assets/7dad9bb7-dfc6-4919-855e-a7bb129a6dae)

**Comment by TheLinuxITGuy** [comment]
Check out 2.0.5
